# This is a basic workflow to help you get started with Actions

name: "tagged-release" 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Duplicate source file
        run: for FILE in "EN" "FR"; do cp ferdi-resume.tex ferdi-resume-$FILE.tex; done
      
      - name: Create the EN source file
        run: sed -i 's/\toggletrue{french}/#\toggletrue{french}/' ferdi-resume-EN.tex
          
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ferdi-resume-EN.tex
            ferdi-resume-FR.tex
          latexmk_use_xelatex: true
      
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ferdi-resume-EN.pdf
            ferdi-resume-FR.pdf
          automatic_release_tag: "latest"
