# This is a basic workflow to help you get started with Actions

name: "test-build" 

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the test-build branch
  push:
    branches: [ test-build ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install fonts
        run: sudo apt-get -y install tex-gyre
  
      - name: Duplicate source file
        run: for FILE in "EN" "FR"; do cp ferdi-resume.tex ferdi-resume-$FILE.tex; done
      
      - name: Delete line 27 in EN template
        run: sed -i '27d' ferdi-resume-EN.tex
          
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ferdi-resume-EN.tex
            ferdi-resume-FR.tex
          latexmk_use_xelatex: true
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: updated-resume
          
      - name: Display structure of downloaded files
        run: ls -R
